on: push
name: Jenkins single-shot master
jobs:
  jenkinsfile-runner-prepackaged:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependences with Yarn
      run: yarn install

    - uses: actions/checkout@master
    - name: Jenkinsfile Runner Prepackaged
      uses: jenkinsci/jenkinsfile-runner-github-actions@v0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}